CREATE DATABASE IF NOT EXISTS balingasag_library
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE balingasag_library;

CREATE TABLE IF NOT EXISTS books (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  category VARCHAR(120) NOT NULL,
  isbn VARCHAR(40) NULL,
  published_year SMALLINT UNSIGNED NULL,
  available_copies INT UNSIGNED NOT NULL DEFAULT 0,
  total_copies INT UNSIGNED NOT NULL DEFAULT 0,
  borrow_count INT UNSIGNED NOT NULL DEFAULT 0,
  description TEXT NULL,
  cover VARCHAR(80) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  role ENUM('admin', 'member') NOT NULL DEFAULT 'member',
  phone VARCHAR(40) NULL,
  joined_at DATE NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  book_id INT UNSIGNED NULL,
  user_name VARCHAR(160) NULL,
  book_title VARCHAR(255) NULL,
  borrowed_at DATE NOT NULL,
  due_at DATE NOT NULL,
  returned_at DATE NULL,
  renewals INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('Active', 'Overdue', 'Completed') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT transactions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT transactions_book_fk FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS fines (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  transaction_id INT UNSIGNED NULL,
  user_name VARCHAR(160) NULL,
  amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  reason VARCHAR(255) NULL,
  created_on DATE NOT NULL,
  paid_on DATE NULL,
  payment_method VARCHAR(80) NULL,
  status ENUM('Paid', 'Unpaid', 'Waived') NOT NULL DEFAULT 'Unpaid',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fines_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fines_transaction_fk FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS notifications (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  type VARCHAR(40) NOT NULL DEFAULT 'bell',
  title VARCHAR(160) NOT NULL,
  message TEXT NOT NULL,
  notification_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT notifications_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reservations (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  book_id INT UNSIGNED NOT NULL,
  status ENUM('Pending', 'Ready', 'Cancelled', 'Completed') NOT NULL DEFAULT 'Pending',
  reserved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT reservations_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT reservations_book_fk FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);
